### ISSUE TITLE
Type streams empty?

### ISSUE THREAD

**Issue by sardaukar** [RailsEventStore/cqrs-es-sample-with-res#27]
Running the demo, I see that even after creating several order, all type streams are empty. What am I doing wrong? Example for one of the types:

![image](https://user-images.githubusercontent.com/153407/114418076-12f93680-9baa-11eb-89fb-e82ba8313c55.png)

![image](https://user-images.githubusercontent.com/153407/114418351-5784d200-9baa-11eb-9cd1-e2977c8eb8a6.png)

![image](https://user-images.githubusercontent.com/153407/114418211-315f3200-9baa-11eb-91a2-8c706357d1fc.png)

**Comment by pawelpacana** [comment]
Hey, it seems that we forgot to add subscribers to create such streams. New apps from [template](https://raw.githubusercontent.com/RailsEventStore/rails_event_store/master/APP_TEMPLATE) have them already enabled:

```ruby
  # Subscribe event handlers below
  Rails.configuration.event_store.tap do |store|
    # store.subscribe(InvoiceReadModel.new, to: [InvoicePrinted])
    # store.subscribe(lambda { |event| SendOrderConfirmation.new.call(event) }, to: [OrderSubmitted])
    # store.subscribe_to_all_events(lambda { |event| Rails.logger.info(event.event_type) })

    store.subscribe_to_all_events(RailsEventStore::LinkByEventType.new)
    store.subscribe_to_all_events(RailsEventStore::LinkByCorrelationId.new)
    store.subscribe_to_all_events(RailsEventStore::LinkByCausationId.new)
  end
```

Behind the scenes these "of type" streams are made with [linking](https://railseventstore.org/docs/v2/link/): https://github.com/RailsEventStore/rails_event_store/blob/0c0e0d35fe5925c587b92c10e3707c9719fae61c/ruby_event_store/lib/ruby_event_store/link_by_metadata.rb#L43-L55

Enabling them for sample application would be a great contribution.

Perhaps Browser should also be improved to not suggest such browsing streams if they don't exist. That's something to be changed within RailsEventStore. Aside: application can suggest related streams for the Browser to display: https://railseventstore.org/docs/v2/browser/#related-streams

**Comment by sardaukar** [comment]
Thanks for the quick reply! Tangential question: why put the code for this example in `lib` and `app/{commands,events,aggregates}`?

**Comment by pawelpacana** [comment]
> Thanks for the quick reply! Tangential question: why put the code for this example in `lib` and not `app/{commands,events,aggregates}`?

We're aiming to group by bounded contexts (i.e. kitchen, bathroom) in this application, rather than group by technical belonging (sinks, lights). Ultimately our goal is to lift those contexts outside rails application directory.

Related:
- https://blog.arkency.com/rails-components-neither-engines-nor-gems/
- https://martinfowler.com/bliki/BoundedContext.html
- https://www.youtube.com/watch?v=arsK-CN5YDg  # wroc_love.rb 2013 | The Not-So-Big Software Design by Reginald Braithwaite
- https://www.youtube.com/watch?v=WpkDN78P884 # Ruby Midwest 2011 | Architecture the Lost Years by Robert Martin
