### ISSUE TITLE
Move from CRUD actions in the controller

### ISSUE THREAD

**Issue by antonpaisov** [RailsEventStore/cqrs-es-sample-with-res#9]
It feels to me that considering the CQRS part of the app, it may be better to avoid rails resources, and replace `index`, `show`, `new` and `create` with some kinds of commands?
I'm talking about `orders_controller`.

Or am I wrong here?

**Comment by antonpaisov** [comment]
There's an opinion that CRUD actions are intentional there. Is it correct?

**Comment by pawelpacana** [comment]
Yes, they were intentional to show how the concept blends into Rails defaults. However when adding new features feel free to introduce non-restful controller actions.
